//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Bill_Customer = new HashSet<Bill_Customer>();
            this.Ords = new HashSet<Ord>();
            this.Recipients = new HashSet<Recipient>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string Ward { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Bill_Customer> Bill_Customer { get; set; }
        public virtual ICollection<Ord> Ords { get; set; }
        public virtual ICollection<Recipient> Recipients { get; set; }
    }
}
