//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Picture_NameGroup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Place { get; set; }
        public string Tag { get; set; }
        public string Image { get; set; }
        public System.DateTime SDate { get; set; }
        public bool Index { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public int Ord { get; set; }
        public Nullable<int> IdCategory2 { get; set; }
        public int IdCategory { get; set; }
        public string Expr1 { get; set; }
    }
}
